### ISSUE TITLE
select root folder and filter lists ?

### ISSUE THREAD

**Issue by b2renger** [pif/android-select-file#2]
Hello ,

I would like to know if there is the possibility to select a root folder for the select dialog to open to ? 

I'm also looking for a way to  filter the results by type of file, say ".mp3" and ".csv" for instance. I have browsed the source code and have seen that there are methods to filter results, but they are not exposed to the processing side of things.

I've imported the classes as a package in eclipse to be able to modify them, but I don't seem to get it.
For instance what is the third argument in

``` java
selectImpl(prompt, callback, null, SelectMode.SELECT_FILE);
```

I believe it's a preselection of a file ? would I be able to pass a path there ?

**Comment by b2renger** [comment]
ok so yes it is possible :) I should just have tried that ...

I'll try to see if I could expose the file filters.

Would you be interested on a pr in the end ?

**Comment by pif** [comment]
Hi, @b2renger !
API was designed with existing Processing selectX() APIs in mind back then.
You could probably add new ones and send PR later on.
Thanks, Ostap

**Comment by b2renger** [comment]
ok so I have some working code, it still needs a bit of polishing, but I was wondering what would be the best names for the new functions ?

I'm thinking :
void customInput(String prompt, String callback, String path2folder)
void customOutput(String prompt, String callback, String path2folder)
void filteredInput (String prompt, String callback, String path2folder , String extension)

What do you think ?

**Comment by b2renger** [comment]
I went for it !

the pr is here : https://github.com/pif/android-select-file/pull/3

hope everything is ok, and thank you for this great lib !
