### ISSUE TITLE
example can not run on Android device.

### ISSUE THREAD

**Issue by bizkitj** [pif/android-select-file#4]
example sketch, select, can not run on Processing 3.2.3, Android SDK API 4.0.4 (15).

Android phone is on Android 6.0.

Please help.

**Comment by pif** [comment]
It's been a while since I last looked at this plugin.
@bizkitj, do you have any logs why is it failing?

**Comment by bizkitj** [comment]
@pif
I am very new to processing and Android mode. I am not sure if this (Processing console ) is the log you are talking about. 












    [mkdir] Created dir: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin
     [echo] org.eclipse.jdt.core.JDTCompilerAdapter

-set-mode-check:

-set-debug-files:

-check-env:
Android SDK Tools Revision 25.2.4
Installed at G:\Program Files\tools_r25.2.3-windows

-setup:
     [echo] Project Name: Select
Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
Using latest Build Tools: 25.0.2
     [echo] Resolving Build Target for Select...
Project Target:   Android 4.0.3
API level:        15
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res
    [mkdir] Created dir: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\rsObj
    [mkdir] Created dir: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\rsLibs
    [mkdir] Created dir: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\gen
    [mkdir] Created dir: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\classes
    [mkdir] Created dir: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for Select...
Library dependencies:
No Libraries

------------------
API<=15: Adding annotations.jar to the classpath.
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
Merging AndroidManifest files into one.
Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 4 source files to C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\classes
----------
1. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\MainActivity.java (at line 9)
	import android.content.pm.PackageManager;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import android.content.pm.PackageManager is never used
----------
2. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\MainActivity.java (at line 11)
	import android.support.v4.content.ContextCompat;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import android.support.v4.content.ContextCompat is never used
----------
3. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\MainActivity.java (at line 13)
	import android.app.AlertDialog;
	       ^^^^^^^^^^^^^^^^^^^^^^^
The import android.app.AlertDialog is never used
----------
4. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\MainActivity.java (at line 14)
	import android.content.DialogInterface;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import android.content.DialogInterface is never used
----------
5. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\MainActivity.java (at line 15)
	import android.Manifest;
	       ^^^^^^^^^^^^^^^^
The import android.Manifest is never used
----------
6. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\MainActivity.java (at line 49)
	int check;
	    ^^^^^
The value of the local variable check is not used
----------
----------
7. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\Select.java (at line 4)
	import processing.data.*; 
	       ^^^^^^^^^^^^^^^
The import processing.data is never used
----------
8. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\Select.java (at line 5)
	import processing.event.*; 
	       ^^^^^^^^^^^^^^^^
The import processing.event is never used
----------
9. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\Select.java (at line 6)
	import processing.opengl.*; 
	       ^^^^^^^^^^^^^^^^^
The import processing.opengl is never used
----------
10. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\Select.java (at line 10)
	import java.util.HashMap; 
	       ^^^^^^^^^^^^^^^^^
The import java.util.HashMap is never used
----------
11. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\Select.java (at line 11)
	import java.util.ArrayList; 
	       ^^^^^^^^^^^^^^^^^^^
The import java.util.ArrayList is never used
----------
12. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\Select.java (at line 13)
	import java.io.BufferedReader; 
	       ^^^^^^^^^^^^^^^^^^^^^^
The import java.io.BufferedReader is never used
----------
13. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\Select.java (at line 14)
	import java.io.PrintWriter; 
	       ^^^^^^^^^^^^^^^^^^^
The import java.io.PrintWriter is never used
----------
14. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\Select.java (at line 15)
	import java.io.InputStream; 
	       ^^^^^^^^^^^^^^^^^^^
The import java.io.InputStream is never used
----------
15. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\Select.java (at line 16)
	import java.io.OutputStream; 
	       ^^^^^^^^^^^^^^^^^^^^
The import java.io.OutputStream is never used
----------
16. WARNING in C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\src\processing\test\select\Select.java (at line 17)
	import java.io.IOException; 
	       ^^^^^^^^^^^^^^^^^^^
The import java.io.IOException is never used
----------
16 problems (16 warnings)

-post-compile:

-obfuscate:

-dex:
input: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\classes
input: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\libs\SelectFile.jar
input: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\libs\android-support-v4.jar
input: G:\Program Files\tools_r25.2.3-windows\tools\support\annotations.jar
input: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\libs\processing-core.jar
Pre-Dexing C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\libs\SelectFile.jar -> SelectFile-a192fb600620559801ae84d37e13c3f5.jar
Pre-Dexing C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\libs\android-support-v4.jar -> android-support-v4-855b2b2840ded4e7be96f716c78e2b86.jar
Pre-Dexing G:\Program Files\tools_r25.2.3-windows\tools\support\annotations.jar -> annotations-e59a62710484533672bd6c5663bfcecd.jar
Pre-Dexing C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\libs\processing-core.jar -> processing-core-67f0dc22f5f972b3a31bfb1544be1afc.jar
Converting compiled files and external libraries into C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\classes.dex...
       [dx] Merged dex #1 (8 defs/4.9KiB)
       [dx] Merged dex #2 (17 defs/16.0KiB)
       [dx] Merged dex #3 (1153 defs/1127.0KiB)
       [dx] Merged dex #4 (2 defs/1.1KiB)
       [dx] Merged dex #5 (171 defs/703.5KiB)
       [dx] Result is 1351 defs/2267.7KiB. Took 0.4s

-crunch:
   [crunch] Crunching PNG Files in source dir: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\res
   [crunch] To destination dir: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res
   [crunch] Processing image to cache: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\res\drawable-hdpi\icon.png => C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable-hdpi\icon.png
   [crunch]   (processed image to cache entry C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable-hdpi\icon.png: 52% size of source)
   [crunch] Processing image to cache: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\res\drawable-ldpi\icon.png => C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable-ldpi\icon.png
   [crunch]   (processed image to cache entry C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable-ldpi\icon.png: 0% size of source)
   [crunch] Processing image to cache: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\res\drawable-xhdpi\icon.png => C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable-xhdpi\icon.png
   [crunch]   (processed image to cache entry C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable-xhdpi\icon.png: 74% size of source)
   [crunch] Processing image to cache: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\res\drawable-xxhdpi\icon.png => C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable-xxhdpi\icon.png
   [crunch]   (processed image to cache entry C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable-xxhdpi\icon.png: 89% size of source)
   [crunch] Processing image to cache: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\res\drawable-xxxhdpi\icon.png => C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable-xxxhdpi\icon.png
   [crunch]   (processed image to cache entry C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable-xxxhdpi\icon.png: 89% size of source)
   [crunch] Processing image to cache: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\res\drawable\icon.png => C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable\icon.png
   [crunch]   (processed image to cache entry C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\res\drawable\icon.png: 84% size of source)
   [crunch] Crunched 6 PNG files to update cache

-package-resources:
Creating full resource package...
     [aapt] Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

-package:
Current build type is different than previous build: forced apkbuilder run.
Creating Select-debug-unaligned.apk and signing it with a debug key...

-post-package:

-do-debug:
Running zip align on final apk...
     [echo] Debug Package: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\Select-debug.apk
[propertyfile] Creating new property file: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\build.prop
[propertyfile] Updating property file: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\build.prop
[propertyfile] Updating property file: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\build.prop
[propertyfile] Updating property file: C:\Users\Jeason\AppData\Local\Temp\android5311951590710505677sketch\bin\build.prop

-post-build:

debug:

**Comment by pif** [comment]
Fixed in v0.0.2 of plugin http://andrusiv.com/android-select-file/
