### ISSUE TITLE
This lib does not work with the Processing APDE app.

### ISSUE THREAD

**Issue by EmmanuelPil** [pif/android-select-file#7]
Installing the lib in the APDE gives the error "Poorly formated library.
I have several libs installed without problems.
Could you please tell me how to rearange the files in this lib?

**Comment by pif** [comment]
@EmmanuelPil Which version of PDE, library and platform do you use?

Just checked with PDE 3.3.7 and SelectFile 0.0.2 from Library manager -- everything worked as expected.

**Comment by EmmanuelPil** [comment]
@pif   I am not using the PDE for a PC but the app APDE because this app compiles sketches in seconds.
I am using a Samsung Tablet Tab E with KitKat.

**Comment by pif** [comment]
@EmmanuelPil I tried installing the library into APDE app v0.4.1 (latest) via:

Menu -> Tools -> Import Library -> Manage Libraries -> Get Libraries -> downloaded latest from [http://andrusiv.com/android-select-file/download/SelectFile.zip](http://andrusiv.com/android-select-file/download/SelectFile.zip) via Chrome -> [back to APDE] Install Compressed Library -> SelectFile was successfully imported. 

Everything worked as expected. 

1. Can you try importing on a different device?
2. Can you share console log from APDE app when the library is not imported?

**Comment by EmmanuelPil** [comment]
Yes, I tried it exactly as suggested above, but it gives a message on the screen:
 `Install failed Library instalation failed. This is usially caused by a poorly formated library. Please see the console for a stack trace.`
Then in the console is  displayed:

```
Unable to locate the library JAR files at "/storage/emulated/0/Sketchbook/libraries/android-select-file-master/library"
Try organizing the folder structure according the Processing library formatting guidelines.
java.lang.NullPointerException
	at com.calsignlabs.apde.contrib.Library.getLibraryJarNames(Library.java:155)
	at com.calsignlabs.apde.contrib.Library.getLibraryJars(Library.java:111)
	at com.calsignlabs.apde.contrib.ContributionManager.installZipLibrary(ContributionManager.java:98)
	at com.calsignlabs.apde.LibraryManagerActivity$15.run(LibraryManagerActivity.java:641)
	at java.lang.Thread.run(Thread.java:841)
```

I have tried this also on my phone with Lollipop 5.1  giving the same problem.

**Comment by pif** [comment]
@EmmanuelPil This folder looks strange `android-select-file-master`. How did you install the library? Maybe, you downloaded .zip from Github, but not from the website.

I have the library at `.../Sketchbook/libraries/SelectFile/library`. Make sure you installed the library following the steps I mentioned earlier and using the link mentioned there.

**Comment by EmmanuelPil** [comment]
OK. It's working right away now. What I did was fistly opening  manage libraries/get libraries.
This leads you to the  processing library page: https://processing.org/reference/libraries
And there you will find a link to the github page where you can download this master zip file that does not install.  Maybe you should change the link in the processing lib page with the link in your previous post. The Ketai lib for instance leads to their home page.
Thanks for the lib. Great contribution.

**Comment by pif** [comment]
@EmmanuelPil thanks for the steps. I'll ask libraries page maintainer for the link update. 

If you'll have any ideas for improvement or feedback after using the library, please share them here.
